#! /bin/sh

# Run python script directly from git.
# Written by Pavel Raiskup.

# Copyright (C) 2018 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

absdir="$(dirname "$(readlink -f "$0")")"

export PYTHONPATH="$absdir${PYTHONPATH+:$PYTHONPATH}"
export PYTHON
export PATH="$absdir${PATH+:$PATH}"

find_prog ()
{
    _old_IFS=$IFS
    find_prog_result=
    IFS=:
    for _dir in $PATH; do
        test -x "$_dir/$1" || continue
        find_prog_result="$_dir/$1"
        break
    done
    IFS=$_old_IFS
}

# Prefer Python 3 if possible.
for _python in python3 python2 python; do
    test -z "$PYTHON" || break
    find_prog "$_python"
    PYTHON=$find_prog_result
done

test -n "$PYTHON" || {
    echo >&2 "python not found in $PATH"
    exit 1
}

exec "$PYTHON" "$absdir/bin/$(basename "$0")" "$@"
